In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/hotelreviews/hotel-reviews.csv


In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import re

In [3]:
dataset=pd.read_csv('/kaggle/input/hotelreviews/hotel-reviews.csv')

In [4]:
dataset.describe()

User_ID                                        Description  \
count     38932                                              38932   
unique    38932                                              38932   
top     id20188  Stayed at this hotel for - nights prior to my ...   
freq          1                                                  1   

       Browser_Used Device_Used Is_Response  
count         38932       38932       38932  
unique           11           3           2  
top         Firefox     Desktop       happy  
freq           7367       15026       26521

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38932 entries, 0 to 38931
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   User_ID       38932 non-null  object
 1   Description   38932 non-null  object
 2   Browser_Used  38932 non-null  object
 3   Device_Used   38932 non-null  object
 4   Is_Response   38932 non-null  object
dtypes: object(5)
memory usage: 1.5+ MB


In [6]:
from nltk.corpus import stopwords

In [7]:
stopWords = stopwords.words('english')

In [8]:
def cleanData(sentence):
    processedList = ""
    
    # convert to lowercase, ignore all special characters - keep only alpha-numericals and spaces (not removing full-stop here)
    sentence = re.sub(r'[^A-Za-z0-9\s.]',r'',str(sentence).lower())
    sentence = re.sub(r'\n',r' ',sentence)
    
    # remove stop words
    sentence = " ".join([word for word in sentence.split() if word not in stopWords])
    
    return sentence

In [9]:
corpus=[]
for i in range(38932):
    x=cleanData(dataset['Description'][i])
    corpus.append(x)

    
    

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500)

In [11]:
dataset['Is_Response'].value_counts()
 

happy        26521
not happy    12411
Name: Is_Response, dtype: int64

In [12]:
for i in range(38932):
    if(dataset['Is_Response'][i]=="happy"):
        dataset['Is_Response'][i]=1
    else:
        dataset['Is_Response'][i]=0

In [13]:
X = cv.fit_transform(corpus).toarray()

In [14]:
dataset['Is_Response'] = dataset['Is_Response'].astype(int)
y = dataset['Is_Response'].values


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)





In [16]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)


GaussianNB()

In [17]:
y_pred = classifier.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [19]:
cm

array([[1635,  867],
       [ 654, 4631]])

In [20]:
# from sklearn.svm import SVC, LinearSVC

In [21]:
# svc = SVC()
# svc.fit(X_train, y_train)
# y_pred1 = svc.predict(X_test)

In [22]:
# from sklearn.metrics import confusion_matrix
# cm = confusion_matrix(y_test, y_pred1)

In [24]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)


/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [25]:
y_pred1 = logreg.predict(X_test)

In [26]:
cm = confusion_matrix(y_test, y_pred1)

In [27]:
cm

array([[1897,  605],
       [ 398, 4887]])

In [28]:
from sklearn.linear_model import Perceptron

In [29]:
perceptron = Perceptron()
perceptron.fit(X_train, y_train)

Perceptron()

In [30]:
y_pred2 = perceptron.predict(X_test)

In [31]:
cm = confusion_matrix(y_test, y_pred2)

In [32]:
cm

array([[1914,  588],
       [ 647, 4638]])

In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
model=KNeighborsClassifier() 
model.fit(X_train, y_train)


KNeighborsClassifier()

In [38]:
y_pred3 = perceptron.predict(X_test)

In [39]:
cm1 = confusion_matrix(y_test, y_pred3)

In [40]:
cm1

array([[1914,  588],
       [ 647, 4638]])

In [52]:
y_pred = y_pred.astype(int)
y_pred1 = y_pred1.astype(int)
y_pred3 = y_pred3.astype(int)
from statistics import mode 
import numpy
final_pred = np.array([])
for i in range(0,7787):
    final_pred = np.append(final_pred, mode([y_pred3[i],y_pred[i],y_pred1[i]]))

In [53]:
final_pred

array([1., 0., 1., ..., 0., 0., 0.])

In [54]:
cm = confusion_matrix(y_test,final_pred)

In [55]:
cm

array([[1895,  607],
       [ 415, 4870]])

ValueError: Input 0 of layer conv2d_3 is incompatible with the layer: expected ndim=4, found ndim=3. Full shape received: [None, 7787, 2500]

In [64]:
X_test.shape

(7787, 2500)

In [93]:
import urllib
link = 'https://github.com/Tanmay18g/Machine-learning/blob/master/Digit%20Recognizer/Digit%20Recognizer.ipynb'
f=urllib.request.urlopen(link)
myfile = f.readlines()  
print (myfile)

[b'<!DOCTYPE html>\r\n', b'\r\n', b'\r\n', b'    <html itemscope itemtype="http://schema.org/QAPage" class="html__responsive">\r\n', b'\r\n', b'    <head>\r\n', b'\r\n', b'        <title>How can I read the contents of an URL with Python? - Stack Overflow</title>\r\n', b'        <link rel="shortcut icon" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196">\r\n', b'        <link rel="apple-touch-icon" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a">\r\n', b'        <link rel="image_src" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a"> \r\n', b'        <link rel="search" type="application/opensearchdescription+xml" title="Stack Overflow" href="/opensearch.xml">\r\n', b'        <link rel="canonical" href="https://stackoverflow.com/questions/15138614/how-can-i-read-the-contents-of-an-url-with-python" />\r\n', b'        <meta name="viewport" content="width=device-width, height=